### ISSUE TITLE
Suggestion to change the repository's name 

### ISSUE THREAD

**Issue by lh1008** [monero-outreach/outreach-docs#4]
I proposed adding the `Contribute` repository to the [Monero Ecosystem Organization](https://github.com/monero-ecosystem)([issue #7](https://github.com/monero-ecosystem/meta/issues/7)). You can read about what is the purpose of the Monero Ecosystem [here](https://github.com/monero-ecosystem/meta).

I suggest we change the repository's name so we can be recognized inside the Monero Ecosystem, I feel the `Contribute` name is something more general :bowtie:. Do you think this might be a good idea?

Maybe 

 - monero-outreach-docs 
 - outreach-docs

Maybe more suggestions... :upside_down_face: :sunglasses:

**Comment by lh1008** [comment]
Hey guys, 

On wire I shared this issue so we can keep on moving with this. @xmrhaelan agreed with "outreach-docs"


What do you guys think? 

@Thunderosa @pet3r-pan @xmrhaelan @UnAidedSage

**Comment by UnAidedSage** [comment]
Like it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lh1008** [comment]
Ok guys, changed the name so we can get going with merging the repository with Monero Ecosystem :).

close #4

**Comment by lh1008** [comment]
Ok guys, changed the name so we can get going with merging the repository with Monero Ecosystem :).

+close #4
